# Generated by Django 3.2.9 on 2021-11-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Entre o titulo', max_length=100)),
                ('data', models.IntegerField(help_text='Entre a data')),
                ('texto', models.CharField(help_text='Entre sua publicação', max_length=100000)),
            ],
        ),
    ]
