# Generated by Django 3.2.9 on 2021-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacoes',
            name='data',
            field=models.DateField(help_text='Entre a data'),
        ),
    ]
