# Generated by Django 3.2.9 on 2021-11-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Entre com o seu nome', max_length=100)),
                ('age', models.IntegerField(help_text='Entre com a sua idade')),
                ('email', models.EmailField(help_text='Entre com o seu email', max_length=254)),
            ],
        ),
    ]
