# Generated by Django 3.2.9 on 2021-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(help_text='Entre com a sua idade', verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Entre com o seu nome', max_length=100, verbose_name='Nome'),
        ),
    ]
