# Generated by Django 3.2.9 on 2021-11-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211128_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(help_text='Entre com a sua idade', null=True, verbose_name='Idade'),
        ),
    ]
